name: Update Data
on:
  schedule:
    - cron: "0 23 * * SUN" # At 11:00 PM, only on Sunday
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: yarn
    
    - name: Copy production env
      run: 'echo -e "${{secrets.ENV}}" > .env'

    - name: Update Dining Menu
      run: yarn fetch:dining
    
    - name: Commit Changes
      uses: EndBug/add-and-commit@v4.4.0
      with:
        author_name: 'Ashoka Tech Min'
        message: 'Update Dining Menu'
        push: true
        add: '.'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}